Repository XanaduAI/strawberryfields, pull requests merged in 2019-08, with the labels that each got.

#156 Change `Program.target` to a property, and ensure run options are saved to Blackbird scripts
  strawberryfields/io.py
  strawberryfields/program.py
  tests/frontend/test_io.py
Labels: review-ready

#160 Added test for cubic phase gate
  tests/backend/test_nongaussian_gates.py
Labels: review-ready, tests

#152 Adds Torontonian sampling support to the Gaussian backend
  .github/CHANGELOG.md
  doc/conf.py
  doc/gallery/scattershot-boson-sampling/scattershot-bs.ipynb
  doc/installing.rst
  doc/tutorials/tutorial_boson_sampling.rst
  doc/tutorials/tutorial_gaussian_boson_sampling.rst
  requirements.txt
  setup.py
  strawberryfields/__init__.py
  strawberryfields/backends/base.py
  strawberryfields/backends/gaussianbackend/backend.py
  strawberryfields/backends/gaussianbackend/ops.py
  strawberryfields/backends/tfbackend/__init__.py
  strawberryfields/circuitspecs/gaussian.py
  strawberryfields/circuitspecs/gbs.py
  strawberryfields/decompositions.py
  strawberryfields/ops.py
  tests/backend/test_tf_import.py
  tests/backend/test_threshold_measurement.py
  tests/frontend/test_about.py
  tests/frontend/test_ops_decompositions.py
Labels: backend, review-ready

#164 Introduce applications layer
  .github/CHANGELOG.md
  .travis.yml
  Makefile
  doc/code/apps/graph.dense.rst
  doc/code/apps/graph.resize.rst
  doc/code/apps/graph.sample.rst
  doc/code/apps/graph.utils.rst
  doc/code/apps/sample.rst
  doc/references.bib
  setup.py
  strawberryfields/apps/__init__.py
  strawberryfields/apps/graph/__init__.py
  strawberryfields/apps/graph/dense.py
  strawberryfields/apps/graph/resize.py
  strawberryfields/apps/graph/sample.py
  strawberryfields/apps/graph/utils.py
  strawberryfields/apps/sample.py
  tests/apps/conftest.py
  tests/apps/test_graph_dense.py
  tests/apps/test_graph_resize.py
  tests/apps/test_graph_sample.py
  tests/apps/test_graph_utils.py
  tests/apps/test_sample.py
  tests/pytest.ini
Labels: applications

#169 Incorrect order in decomposition of CXgate
  doc/conventions/gates.rst
Labels: docs

#154 Removes the restriction of zero mean for PNR sampling
  .github/CHANGELOG.md
  strawberryfields/backends/gaussianbackend/backend.py
  strawberryfields/backends/gaussianbackend/gaussiancircuit.py
  tests/backend/test_fock_measurement.py
  tests/integration/test_measurement_integration.py
Labels: backend

#176 Add clique_shrink function to graph apps
  strawberryfields/apps/graph/resize.py
  tests/apps/test_graph_resize.py
Labels: applications, review-ready
