Repository XanaduAI/strawberryfields, pull requests merged in 2019-11, with the labels that each got.

#229 GBS: Fix sample warning
  strawberryfields/gbs/sample.py
Labels: applications, review-ready

#230 GBS Docs: Add plotting note to tutorial
  examples_gbs/run_tutorial_dense.py
  examples_gbs/run_tutorial_max_clique.py
  examples_gbs/run_tutorial_points.py
  examples_gbs/run_tutorial_sample.py
  examples_gbs/run_tutorial_similarity.py
Labels: applications, docs, review-ready

#243 Compute two-mode squeezing parameters
  strawberryfields/gbs/vibronic.py
  tests/gbs/test_vibronic.py
Labels: applications, review-ready

#244 Compute vibronic energies at finite temperature
  strawberryfields/gbs/vibronic.py
  tests/gbs/test_vibronic.py
Labels: applications, review-ready

#245 Add vibronic sampler for finite temperature
  strawberryfields/gbs/sample.py
  tests/gbs/test_sample.py
Labels: applications, review-ready

#236 GBS: Add spectrum plotting functionality
  strawberryfields/gbs/plot.py
  tests/gbs/test_plot.py
Labels: applications, review-ready

#248 Modify vibronic plot xaxis
  strawberryfields/gbs/plot.py
Labels: applications, review-ready

#241 GBS: Add vibronic dataset
  doc/_static/formic.png
  doc/references.bib
  strawberryfields/gbs/data.py
  strawberryfields/gbs/data/formic.npz
  strawberryfields/gbs/data/formic_Ud.npz
  strawberryfields/gbs/data/formic_delta.npz
  strawberryfields/gbs/data/formic_w.npz
  strawberryfields/gbs/data/formic_wp.npz
  tests/gbs/test_data.py
Labels: applications, review-ready

#250 WIP: Intro to GBS in docstrings
  doc/gbs_intro.rst
  doc/index.rst
Labels: WIP, applications

#246 GBS: Tutorial for vibronic spectra
  doc/_static/thumbs/spectrum.png
  doc/gbs_tutorials.rst
  examples_gbs/run_tutorial_vibronic.py
  strawberryfields/gbs/vibronic.py
Labels: applications

#251 Version bump to v0.11.2
  .github/CHANGELOG.md
  doc/conf.py
  doc/index.rst
  examples_gbs/README.txt
  examples_gbs/run_tutorial_dense.py
  examples_gbs/run_tutorial_max_clique.py
  examples_gbs/run_tutorial_points.py
  examples_gbs/run_tutorial_sample.py
  examples_gbs/run_tutorial_similarity.py
  examples_gbs/run_tutorial_vibronic.py
  setup.py
  strawberryfields/_version.py
Labels: review-ready

#242 First attempt at decomposing Xgate, Zgate and Fourier
  strawberryfields/circuitspecs/fock.py
  strawberryfields/circuitspecs/gaussian.py
  strawberryfields/circuitspecs/gbs.py
  strawberryfields/circuitspecs/tensorflow.py
  strawberryfields/ops.py
  tests/frontend/test_ops_decompositions.py
Labels: frontend, review-ready

#253 Remove output string from plots
  doc/conf.py
Labels: docs

#254 Fix TF Showing in Docs
  doc/conf.py
Labels: docs, review-ready

#237 Simulon support
  starship
  strawberryfields/api_client.py
  strawberryfields/backends/__init__.py
  strawberryfields/backends/chip0backend/__init__.py
  strawberryfields/backends/chip0backend/backend.py
  strawberryfields/configuration.py
  strawberryfields/engine.py
  strawberryfields/program.py
  tests/frontend/test_configuration.py
  tests/frontend/test_engine.py
Labels: frontend, merge-ready
