Repository XanaduAI/strawberryfields, pull requests merged in 2019-12, with the labels that each got.

#249 Creates a Chip2 circuit spec
  doc/requirements.txt
  strawberryfields/circuitspecs/__init__.py
  strawberryfields/circuitspecs/chip0.py
  strawberryfields/circuitspecs/chip2.py
  tests/frontend/test_circuitspecs_chip2.py
Labels: review-ready

#257 Add virtual backends
  strawberryfields/backends/__init__.py
  strawberryfields/backends/chip0backend/__init__.py
  strawberryfields/backends/chip0backend/backend.py
Labels: backend, frontend, review-ready

#258 Chip2spec now defined in terms of MZgates
  strawberryfields/circuitspecs/chip2.py
  tests/frontend/test_circuitspecs_chip2.py
Labels: review-ready

#259 Apps plotting: allow user to specify both x and y dimension of plots
  strawberryfields/apps/plot.py
Labels: applications, review-ready

#261 Apps: Rename kernel to rbf_kernel
  examples_apps/run_tutorial_points.py
  strawberryfields/apps/points.py
  tests/apps/test_points.py
Labels: applications, review-ready

#260 Apps: add module to SF __init__
  strawberryfields/__init__.py
Labels: applications, review-ready

#267 Version bump to v0.12
  .github/CHANGELOG.md
  strawberryfields/_version.py
Labels: merge-ready

#264 Remove outdated hafnian dependency
  setup.py
Labels: bug

#272 Require thewalrus>=0.9 to fix an import error in the apps module.
  setup.py
Labels: bug

#274 Add paper
  README.rst
  doc/development/research.rst
  doc/index.rst
  doc/references.bib
  doc/xanadu_theme/header.html
Labels: docs, review-ready

#275 Update GBS figure
  doc/_static/GBS.png
  doc/_static/GBS.svg
Labels: docs

#238 Gaussian unitary
  .github/CHANGELOG.md
  requirements.txt
  setup.py
  strawberryfields/circuitspecs/__init__.py
  strawberryfields/circuitspecs/gaussian_unitary.py
  strawberryfields/utils.py
  tests/frontend/test_circuitspecs_gaussianunitary.py
Labels: review-ready

#270 Added Quadrature Values
  .github/CHANGELOG.md
  strawberryfields/backends/states.py
  tests/backend/test_states_wigner.py
Labels: enhancement, frontend, review-ready
