Repository XanaduAI/strawberryfields, pull requests merged in 2019-10, with the labels that each got.

#199 Add graph visualization module
  doc/_static/complete_graph.png
  doc/_static/complete_subgraph.png
  doc/code/gbs/plot.rst
  doc/index.rst
  strawberryfields/gbs/plot.py
  tests/gbs/test_plot.py
Labels: applications, review-ready

#200 Add apps pp kernel matrix
  doc/code/gbs/points.rst
  doc/index.rst
  strawberryfields/gbs/__init__.py
  strawberryfields/gbs/points.py
  tests/gbs/test_points.py
Labels: applications

#201 Add point process sampler
  doc/references.bib
  strawberryfields/gbs/points.py
  tests/gbs/test_points.py
Labels: applications, review-ready

#198 Add GBS data interface and an initial dataset
  doc/_static/planted.png
  doc/code/gbs/data.rst
  doc/index.rst
  setup.py
  strawberryfields/gbs/__init__.py
  strawberryfields/gbs/data.py
  strawberryfields/gbs/data/planted.npz
  strawberryfields/gbs/data/planted_A.npy
  tests/gbs/test_data.py
  tests/gbs/test_plot.py
Labels: applications

#202 Add sphinx-gallery support
  .gitignore
  doc/_static/thumbs/code.png
  doc/_static/xanadu_gallery.css
  doc/conf.py
  doc/custom_directives.py
  doc/gbs_tutorials.rst
  doc/requirements.txt
  examples_gbs/README.txt
  examples_gbs/run_tutorial_example.py
  strawberryfields/gbs/__init__.py
Labels: docs, review-ready

#204 Add more GBS samples from graphs
  doc/_static/graphs/MUTAG_0.png
  doc/_static/graphs/MUTAG_1.png
  doc/_static/graphs/MUTAG_2.png
  doc/_static/graphs/MUTAG_3.png
  doc/_static/graphs/TACE-AS.png
  doc/_static/graphs/planted.png
  doc/_static/planted.png
  doc/references.bib
  strawberryfields/gbs/data.py
  strawberryfields/gbs/data/MUTAG_0.npz
  strawberryfields/gbs/data/MUTAG_0_A.npz
  strawberryfields/gbs/data/MUTAG_1.npz
  strawberryfields/gbs/data/MUTAG_1_A.npz
  strawberryfields/gbs/data/MUTAG_2.npz
  strawberryfields/gbs/data/MUTAG_2_A.npz
  strawberryfields/gbs/data/MUTAG_3.npz
  strawberryfields/gbs/data/MUTAG_3_A.npz
  strawberryfields/gbs/data/TACE-AS.npz
  strawberryfields/gbs/data/TACE-AS_A.npz
  strawberryfields/gbs/data/p_hat300-1.npz
  strawberryfields/gbs/data/p_hat300-1_A.npz
  strawberryfields/gbs/data/planted.npz
  strawberryfields/gbs/data/planted_A.npy
  strawberryfields/gbs/data/planted_A.npz
  tests/gbs/test_data.py
Labels: applications, review-ready

#205 Apps: Adds point process visualization
  doc/_static/normal_pp.png
  strawberryfields/gbs/plot.py
  strawberryfields/gbs/points.py
  strawberryfields/gbs/similarity.py
Labels: applications, review-ready

#207 Refactor sample module
  strawberryfields/gbs/sample.py
  strawberryfields/gbs/subgraph.py
  tests/gbs/test_sample.py
  tests/gbs/test_subgraph.py
Labels: applications, review-ready

#209 Refactor resizing part of subgraph module
  strawberryfields/gbs/sample.py
  strawberryfields/gbs/subgraph.py
  tests/gbs/test_clique.py
  tests/gbs/test_subgraph.py
Labels: applications, review-ready

#211 Apps: Max clique tutorial
  doc/Makefile
  doc/_static/max_clique.png
  doc/gbs_tutorials.rst
  doc/index.rst
  doc/references.bib
  examples_gbs/run_tutorial_example.py
  examples_gbs/run_tutorial_max_clique.py
Labels: applications, review-ready

#206 GBS Tutorial: Graph Similarity
  doc/_static/similarity_svm.png
  doc/gbs_tutorials.rst
  doc/index.rst
  doc/references.bib
  doc/requirements.txt
  doc/zreferences.rst
  examples_gbs/run_tutorial_similarity.py
Labels: applications, review-ready

#215 GBS Tutorial: Sampling
  doc/_static/thumbs/photon.png
  doc/gbs_tutorials.rst
  examples_gbs/run_tutorial_sample.py
Labels: applications, review-ready

#219 Fix plotly rendering
  doc/xanadu_theme/layout.html
Labels: applications, review-ready

#210 GBS Tutorial: Point Process
  doc/_static/points.png
  doc/gbs_tutorials.rst
  doc/requirements.txt
  examples_gbs/run_tutorial_points.py
Labels: applications, review-ready

#212 GBS Docs: Improve similarity docstrings
  doc/references.bib
  examples_gbs/run_tutorial_similarity.py
  strawberryfields/gbs/similarity.py
Labels: applications, review-ready

#217 GBS Docs: Improve sample docstrings
  examples_gbs/run_tutorial_sample.py
  strawberryfields/gbs/sample.py
Labels: applications, merge-ready

#220 Apps: Dense subgraph tutorial
  doc/_static/dense.png
  doc/gbs_tutorials.rst
  examples_gbs/run_tutorial_dense.py
Labels: applications, review-ready

#218 GBS Docs: Improving point process docs
  examples_gbs/run_tutorial_points.py
  strawberryfields/gbs/points.py
Labels: applications, review-ready

#221 GBS Docs: Improving max clique docs
  examples_gbs/run_tutorial_max_clique.py
  strawberryfields/gbs/clique.py
Labels: applications, review-ready

#222 GBS Docs: Improving subgraph docs
  examples_gbs/run_tutorial_dense.py
  strawberryfields/gbs/subgraph.py
Labels: applications, review-ready

#223 GBS: Add ability to simulate losses in GBS
  examples_gbs/run_tutorial_sample.py
  strawberryfields/gbs/data.py
  strawberryfields/gbs/sample.py
  strawberryfields/gbs/similarity.py
  tests/gbs/test_sample.py
  tests/gbs/test_similarity.py
Labels: applications, review-ready

#224 GBS Bug: Fix single shot sampling
  strawberryfields/gbs/sample.py
  tests/gbs/test_sample.py
Labels: applications, bug, review-ready

#226 Fix Readthedocs building
  .readthedocs.yml
  doc/requirements.txt
Labels: docs

#227 GBS: Rename plotting functions
  examples_gbs/run_tutorial_dense.py
  examples_gbs/run_tutorial_max_clique.py
  examples_gbs/run_tutorial_points.py
  examples_gbs/run_tutorial_sample.py
  examples_gbs/run_tutorial_similarity.py
  strawberryfields/gbs/plot.py
Labels: applications

#232 Add io.loads function to load from string
  strawberryfields/io.py
  tests/frontend/test_io.py
Labels: enhancement, frontend

#163 Symbolic Operation parameters using SymPy
  doc/code/code.rst
  doc/index.rst
  strawberryfields/__init__.py
  strawberryfields/backends/tfbackend/backend.py
  strawberryfields/backends/tfbackend/circuit.py
  strawberryfields/circuitspecs/chip0.py
  strawberryfields/engine.py
  strawberryfields/io.py
  strawberryfields/ops.py
  strawberryfields/parameters.py
  strawberryfields/program.py
  strawberryfields/program_utils.py
  strawberryfields/utils.py
  tests/frontend/test_circuitspecs_chip0.py
  tests/frontend/test_io.py
  tests/frontend/test_ops_channel.py
  tests/frontend/test_ops_decompositions.py
  tests/frontend/test_ops_gate.py
  tests/frontend/test_ops_metaoperation.py
  tests/frontend/test_ops_preparation.py
  tests/frontend/test_parameters.py
  tests/frontend/test_program.py
  tests/frontend/test_utils.py
  tests/integration/test_algorithms.py
  tests/integration/test_decompositions_integration.py
  tests/integration/test_engine_integration.py
  tests/integration/test_parameters_integration.py
  tests/integration/test_tf_symbolic.py
Labels: enhancement, frontend, review-ready

#234 Fix sidebar when adverts are showing
  doc/xanadu_theme/static/xanadu.css_t
Labels: docs

#231 Add vibronic module with GBS params function
  doc/code/gbs/vibronic.rst
  doc/index.rst
  doc/references.bib
  strawberryfields/gbs/__init__.py
  strawberryfields/gbs/vibronic.py
  tests/gbs/test_vibronic.py
Labels: applications, review-ready

#233 Add vibronic sampler
  doc/introduction.rst
  examples_gbs/run_tutorial_sample.py
  strawberryfields/gbs/sample.py
  tests/gbs/test_sample.py
Labels: applications, review-ready

#235 Add vibronic energies
  strawberryfields/gbs/vibronic.py
  tests/gbs/test_vibronic.py
Labels: applications, review-ready
