Repository XanaduAI/strawberryfields, pull requests merged in 2019-09, with the labels that each got.

#177 Add example code to docstrings for utils
  doc/conf.py
  strawberryfields/apps/graph/resize.py
  strawberryfields/apps/graph/utils.py
Labels: applications, review-ready

#178 Add example code to docstrings for resize
  strawberryfields/apps/graph/resize.py
Labels: applications, review-ready

#179 Provide local search algorithm for maximum clique
  doc/references.bib
  strawberryfields/apps/graph/max_clique.py
  tests/apps/test_graph_max_clique.py
Labels: applications, review-ready

#180 Provide applications layer in docs and polish max clique documentation
  doc/code/apps/graph.max_clique.rst
  doc/index.rst
  strawberryfields/apps/graph/max_clique.py
  strawberryfields/apps/graph/resize.py
  strawberryfields/apps/graph/utils.py
  strawberryfields/apps/sample.py
Labels: applications, docs

#182 Improving Apps Structure: Part 1 - Remove graph layer and consolidate clique functions
  .travis.yml
  doc/code/apps/graph.dense.rst
  doc/code/apps/graph.max_clique.rst
  doc/code/apps/graph.resize.rst
  doc/code/apps/graph.sample.rst
  doc/code/apps/graph.similarity.rst
  doc/code/apps/graph.utils.rst
  doc/code/apps/sample.rst
  doc/code/gbs/clique.rst
  doc/code/gbs/dense.rst
  doc/code/gbs/g_sample.rst
  doc/code/gbs/resize.rst
  doc/code/gbs/sample.rst
  doc/code/gbs/similarity.rst
  doc/code/gbs/utils.rst
  doc/index.rst
  setup.py
  strawberryfields/apps/graph/__init__.py
  strawberryfields/apps/graph/max_clique.py
  strawberryfields/gbs/__init__.py
  strawberryfields/gbs/clique.py
  strawberryfields/gbs/dense.py
  strawberryfields/gbs/g_sample.py
  strawberryfields/gbs/resize.py
  strawberryfields/gbs/sample.py
  strawberryfields/gbs/similarity.py
  strawberryfields/gbs/utils.py
  tests/apps/test_graph_max_clique.py
  tests/apps/test_graph_resize.py
  tests/gbs/conftest.py
  tests/gbs/test_clique.py
  tests/gbs/test_dense.py
  tests/gbs/test_g_sample.py
  tests/gbs/test_gbs_utils.py
  tests/gbs/test_resize.py
  tests/gbs/test_sample.py
  tests/gbs/test_similarity.py
Labels: applications, review-ready

#183 Provide functionality to randomly sample from events and orbits
  strawberryfields/gbs/similarity.py
  tests/gbs/test_similarity.py
Labels: applications, review-ready

#187 Improving Apps Structure: Part 2 - Consolidate graph density based functions into dense module
  doc/code/gbs/resize.rst
  doc/index.rst
  strawberryfields/gbs/__init__.py
  strawberryfields/gbs/dense.py
  strawberryfields/gbs/g_sample.py
  strawberryfields/gbs/resize.py
  tests/gbs/test_dense.py
  tests/gbs/test_resize.py
Labels: applications, review-ready

#188 Apps layer: Provide feature_vector_sampling
  strawberryfields/gbs/similarity.py
  tests/gbs/test_similarity.py
Labels: applications, review-ready

#191 Circuit drawer fix
  strawberryfields/circuitdrawer.py
  tests/frontend/test_circuitdrawer.py
Labels: enhancement

#173 Adds tests for decomposed frontend gates
  .github/CHANGELOG.md
  tests/integration/test_decompositions_integration.py
Labels: tests

#184 Apps layer: Provide event probabilities calculated by Monte Carlo
  Makefile
  strawberryfields/gbs/g_sample.py
  strawberryfields/gbs/sample.py
  strawberryfields/gbs/similarity.py
  tests/gbs/test_sample.py
  tests/gbs/test_similarity.py
  tests/pytest.ini
Labels: applications, review-ready

#189 Improving Apps Structure: Part 3 - Consolidate sampling based functions into sample module
  doc/code/gbs/g_sample.rst
  strawberryfields/gbs/__init__.py
  strawberryfields/gbs/dense.py
  strawberryfields/gbs/g_sample.py
  strawberryfields/gbs/sample.py
  tests/gbs/test_clique.py
  tests/gbs/test_dense.py
  tests/gbs/test_g_sample.py
  tests/gbs/test_gbs_utils.py
  tests/gbs/test_sample.py
Labels: applications, review-ready

#190 Improving Apps Structure: Part 4
  doc/code/gbs/dense.rst
  doc/code/gbs/subgraph.rst
  doc/code/gbs/utils.rst
  doc/index.rst
  strawberryfields/gbs/__init__.py
  strawberryfields/gbs/clique.py
  strawberryfields/gbs/sample.py
  strawberryfields/gbs/subgraph.py
  strawberryfields/gbs/utils.py
  tests/gbs/test_clique.py
  tests/gbs/test_gbs_utils.py
  tests/gbs/test_sample.py
  tests/gbs/test_subgraph.py
Labels: applications, review-ready

#195 Apps layer: Add feature vector from Monte Carlo
  strawberryfields/gbs/similarity.py
  tests/gbs/test_similarity.py
Labels: applications, review-ready

#194 Apps Layer: Fix event_to_sample
  strawberryfields/gbs/similarity.py
  tests/gbs/test_similarity.py
Labels: applications, review-ready

#196 Fix issue #192 and part of #193 (decompositions.rectangular_*)
  .github/CHANGELOG.md
  strawberryfields/decompositions.py
  tests/frontend/test_decompositions.py
Labels: bug
