Repository XanaduAI/strawberryfields, pull requests merged in 2020-06, with the labels that each got.

#393 Add stochastic cost function to GBS cost module in apps layer
  strawberryfields/apps/train/__init__.py
  strawberryfields/apps/train/cost.py
  tests/apps/test_cost.py
Labels: applications, enhancement, review-ready

#398 Unify backend results
  strawberryfields/api/result.py
  strawberryfields/backends/fockbackend/circuit.py
  strawberryfields/backends/gaussianbackend/backend.py
  strawberryfields/backends/tfbackend/circuit.py
  strawberryfields/engine.py
  strawberryfields/ops.py
  strawberryfields/parameters.py
  tests/backend/test_fock_measurement.py
  tests/backend/test_postselection.py
  tests/backend/test_threshold_measurement.py
  tests/conftest.py
  tests/frontend/test_engine.py
  tests/frontend/test_parameters.py
  tests/integration/test_engine_integration.py
  tests/integration/test_tf_integration.py
Labels: code quality, review-ready

#402 Add qchem and dynamics observable
  doc/references.bib
  requirements.txt
  strawberryfields/apps/__init__.py
  strawberryfields/apps/qchem/__init__.py
  strawberryfields/apps/qchem/dynamics.py
  tests/apps/qchem/test_dynamics.py
Labels: applications, review-ready

#407 Updates BaseGaussianState to be feature compatible with BaseFockState
  .github/CHANGELOG.md
  doc/introduction/states.rst
  requirements.txt
  setup.py
  strawberryfields/backends/gaussianbackend/__init__.py
  strawberryfields/backends/gaussianbackend/backend.py
  strawberryfields/backends/gaussianbackend/gaussiancircuit.py
  strawberryfields/backends/gaussianbackend/ops.py
  strawberryfields/backends/gaussianbackend/states.py
  strawberryfields/backends/states.py
  tests/apps/test_similarity.py
  tests/backend/test_multimode_state_preparations.py
  tests/backend/test_states.py
  tests/backend/test_states_probabilities.py
  tests/integration/test_ops_integration.py
Labels: backend, enhancement, merge-ready

#381 Updates the Fock backend ops.py to use the new Walrus gate signatures
  .github/CHANGELOG.md
  doc/introduction/states.rst
  requirements.txt
  setup.py
  strawberryfields/backends/fockbackend/ops.py
  strawberryfields/backends/gaussianbackend/__init__.py
  strawberryfields/backends/gaussianbackend/backend.py
  strawberryfields/backends/gaussianbackend/gaussiancircuit.py
  strawberryfields/backends/gaussianbackend/ops.py
  strawberryfields/backends/gaussianbackend/states.py
  strawberryfields/backends/states.py
  tests/apps/test_similarity.py
  tests/backend/test_multimode_state_preparations.py
  tests/backend/test_states.py
  tests/backend/test_states_probabilities.py
  tests/integration/test_ops_integration.py
Labels: WIP, backend

#411 Add a function to qchem for Fock state sampling
  .github/CHANGELOG.md
  strawberryfields/apps/qchem/dynamics.py
  tests/apps/qchem/test_dynamics.py
Labels: applications, review-ready

#390 Updating the similarity module functions in the Apps layer
  .github/CHANGELOG.md
  examples_apps/run_tutorial_similarity.py
  strawberryfields/apps/similarity.py
  tests/apps/test_similarity.py
Labels: review-ready

#419 Add a function to qchem for computing state probability
  .github/CHANGELOG.md
  strawberryfields/apps/qchem/dynamics.py
  tests/apps/qchem/test_dynamics.py
Labels: applications, review-ready

#401 Making new class for feature vector datasets
  .github/CHANGELOG.md
  doc/introduction/data.rst
  doc/references.bib
  strawberryfields/apps/data/__init__.py
  strawberryfields/apps/data/feature.py
  strawberryfields/apps/data/feature_data/MUTAG_exact_fv.npy
  strawberryfields/apps/data/feature_data/MUTAG_mat.npy
  strawberryfields/apps/data/feature_data/QM9_exact_fv.npy
  strawberryfields/apps/data/feature_data/QM9_mat.npy
  strawberryfields/apps/data/feature_data/QM9_mc_fv.npy
  strawberryfields/apps/data/sample.py
  strawberryfields/apps/data/sample_data/MUTAG_0.npz
  strawberryfields/apps/data/sample_data/MUTAG_0_A.npz
  strawberryfields/apps/data/sample_data/MUTAG_1.npz
  strawberryfields/apps/data/sample_data/MUTAG_1_A.npz
  strawberryfields/apps/data/sample_data/MUTAG_2.npz
  strawberryfields/apps/data/sample_data/MUTAG_2_A.npz
  strawberryfields/apps/data/sample_data/MUTAG_3.npz
  strawberryfields/apps/data/sample_data/MUTAG_3_A.npz
  strawberryfields/apps/data/sample_data/TACE-AS.npz
  strawberryfields/apps/data/sample_data/TACE-AS_A.npz
  strawberryfields/apps/data/sample_data/formic.npz
  strawberryfields/apps/data/sample_data/formic_Ud.npz
  strawberryfields/apps/data/sample_data/formic_delta.npz
  strawberryfields/apps/data/sample_data/formic_w.npz
  strawberryfields/apps/data/sample_data/formic_wp.npz
  strawberryfields/apps/data/sample_data/p_hat300-1.npz
  strawberryfields/apps/data/sample_data/p_hat300-1_A.npz
  strawberryfields/apps/data/sample_data/planted.npz
  strawberryfields/apps/data/sample_data/planted_A.npz
  tests/apps/test_data.py
Labels: review-ready

#424 Fix docs building
  doc/requirements.txt
  tests/apps/test_similarity.py
Labels: bug

#414 Restructure and improve docs in apps.train module
  doc/references.bib
  strawberryfields/apps/train/__init__.py
  strawberryfields/apps/train/cost.py
  strawberryfields/apps/train/embed.py
Labels: applications, docs, review-ready

#415 Tidy up tests for apps.train module and add to changelog
  .github/CHANGELOG.md
  strawberryfields/apps/train/cost.py
  tests/apps/train/test_cost.py
  tests/apps/train/test_embed.py
  tests/apps/train/test_param.py
Labels: applications, review-ready

#416 Move vibronic into new qchem module
  .github/CHANGELOG.md
  doc/introduction/data.rst
  examples_apps/run_tutorial_vibronic.py
  strawberryfields/apps/__init__.py
  strawberryfields/apps/plot.py
  strawberryfields/apps/qchem/__init__.py
  strawberryfields/apps/qchem/vibronic.py
  strawberryfields/apps/sample.py
  tests/apps/qchem/test_vibronic.py
  tests/apps/test_sample.py
  tests/apps/test_vibronic.py
Labels: applications, review-ready

#425 Make new apps layer datasets loadable when installing SF
  MANIFEST.in
  setup.py
Labels: applications, bug

#421 Add a function to qchem for computing marginals
  .github/CHANGELOG.md
  strawberryfields/apps/qchem/dynamics.py
  tests/apps/qchem/test_dynamics.py
Labels: applications, merge-ready, review-ready
