Repository XanaduAI/strawberryfields, pull requests merged in 2020-03, with the labels that each got.

#283 TF2 compatibility
  .gitignore
  requirements.txt
  strawberryfields/backends/tfbackend/__init__.py
  strawberryfields/backends/tfbackend/backend.py
  strawberryfields/backends/tfbackend/circuit.py
  strawberryfields/backends/tfbackend/ops.py
  strawberryfields/backends/tfbackend/states.py
  strawberryfields/engine.py
  tests/backend/test_states_probabilities.py
  tests/backend/test_tf_import.py
  tests/conftest.py
  tests/frontend/test_ops_gate.py
  tests/integration/test_algorithms.py
  tests/integration/test_engine_integration.py
  tests/integration/test_utils_integration.py
Labels: backend, merge-ready, tensorflow

#311 Rectangular decomposition: Identity fix
  strawberryfields/decompositions.py
Labels: enhancement

#312 Refactoring the starship CLI and adding unit tests
  .github/CHANGELOG.md
  doc/index.rst
  requirements.txt
  setup.py
  starship
  strawberryfields/cli/__init__.py
  tests/frontend/test_starship.py
Labels: bug, enhancement

#313 Update CHANGELOG.md
  .github/CHANGELOG.md
Labels: review-ready

#316 Rename StarshipEngine to RemoteEngine, starship CLI to sf
  .travis.yml
  doc/introduction/configuration.rst
  doc/introduction/remote.rst
  doc/introduction/tutorials.rst
  setup.py
  strawberryfields/__init__.py
  strawberryfields/api/connection.py
  strawberryfields/api/job.py
  strawberryfields/cli/__init__.py
  strawberryfields/configuration.py
  strawberryfields/engine.py
  tests/api/test_starship_engine.py
  tests/frontend/test_circuitspecs_chip2.py
  tests/frontend/test_sf_cli.py
Labels: review-ready

#321 Add apps example
  .github/CHANGELOG.md
Labels: review-ready

#319 Merge the demo branch into master
  .github/CHANGELOG.md
  .gitignore
  .travis.yml
  Makefile
  README.rst
  default_config.toml
  doc/_static/xanadu_gallery.css
  doc/code/sf_api.rst
  doc/code/sf_cli.rst
  doc/code/sf_configuration.rst
  doc/conf.py
  doc/development/release_notes.md
  doc/development/research.rst
  doc/index.rst
  doc/introduction/configuration.rst
  doc/introduction/remote.rst
  doc/introduction/tutorials.rst
  doc/requirements.txt
  doc/tutorials/tutorial_boson_sampling.rst
  doc/tutorials/tutorial_machine_learning.rst
  doc/tutorials/tutorial_post_selection.rst
  doc/tutorials/tutorial_teleportation.rst
  doc/xanadu_theme/layout.html
  doc/xanadu_theme/static/xanadu.css_t
  examples/boson_sampling.py
  requirements.txt
  setup.py
  strawberryfields/__init__.py
  strawberryfields/_dev/configuration.py
  strawberryfields/api/__init__.py
  strawberryfields/api/connection.py
  strawberryfields/api/job.py
  strawberryfields/api/result.py
  strawberryfields/backends/__init__.py
  strawberryfields/circuitspecs/__init__.py
  strawberryfields/circuitspecs/chip0.py
  strawberryfields/circuitspecs/chip2.py
  strawberryfields/cli/__init__.py
  strawberryfields/configuration.py
  strawberryfields/engine.py
  strawberryfields/io.py
  strawberryfields/ops.py
  strawberryfields/program.py
  strawberryfields/program_utils.py
  tests/api/__init__.py
  tests/api/conftest.py
  tests/api/test_connection.py
  tests/api/test_job.py
  tests/api/test_remote_engine.py
  tests/api/test_result.py
  tests/conftest.py
  tests/frontend/test_circuitspecs_chip0.py
  tests/frontend/test_circuitspecs_chip2.py
  tests/frontend/test_circuitspecs_gaussianunitary.py
  tests/frontend/test_configuration.py
  tests/frontend/test_engine.py
  tests/frontend/test_io.py
  tests/frontend/test_sf_cli.py
  tests/pytest.ini
Labels: review-ready

#326 Remove accidental xfail commit from the demo branch
  tests/frontend/test_circuitspecs_gaussianunitary.py
Labels: bug, review-ready, tests

#327 Make shots parameter optional for RemoteEngine and Connection
  .github/CHANGELOG.md
  strawberryfields/api/connection.py
  strawberryfields/engine.py
Labels: API, bug, review-ready

#325 Update changelog
  .github/CHANGELOG.md
Labels: docs

#324 Refactor the configuration and CLI documentation pages
  doc/code/sf_cli.rst
  doc/code/sf_configuration.rst
  doc/index.rst
  doc/introduction/configuration.rst
  doc/introduction/photonic_hardware.rst
  doc/introduction/remote.rst
  strawberryfields/cli/__init__.py
  strawberryfields/configuration.py
Labels: docs

#330 Hardware tutorial
  doc/_static/chip.png
  doc/_static/chip.svg
  doc/introduction/photonic_hardware.rst
  doc/introduction/remote.rst
  doc/introduction/tutorials.rst
  strawberryfields/circuitspecs/gaussian_unitary.py
Labels: docs, review-ready

#336 Fix a json-issue in the cancel_job method of sf.api.connection.Connection
  strawberryfields/api/connection.py
  tests/api/test_connection.py
Labels: review-ready

#337 Unify RemoteEngine.run() and LocalEngine.run() signatures, and allow for default chip specs for each device family.
  doc/algorithms/gaussian_boson_sampling.rst
  doc/gallery/gate_synthesis/GateSynthesis.ipynb
  doc/gallery/minimizing_correlations/minimizing_correlations.ipynb
  doc/gallery/state_learner/StateLearning.ipynb
  doc/tutorials/tutorial_machine_learning.rst
  doc/tutorials/tutorial_teleportation.rst
  examples/GaussianBosonSampling.ipynb
  examples/gaussian_cloning.py
  examples/optimization.py
  examples/quantum_neural_network.py
  strawberryfields/api/connection.py
  strawberryfields/apps/sample.py
  strawberryfields/circuitspecs/X12.py
  strawberryfields/circuitspecs/X8.py
  strawberryfields/circuitspecs/__init__.py
  strawberryfields/engine.py
  strawberryfields/io.py
  strawberryfields/program.py
  tests/api/conftest.py
  tests/api/test_connection.py
  tests/api/test_remote_engine.py
  tests/frontend/test_engine.py
  tests/frontend/test_io.py
  tests/integration/test_algorithms.py
  tests/integration/test_engine_integration.py
  tests/integration/test_measurement_integration.py
  tests/integration/test_ops_integration.py
  tests/integration/test_tf_symbolic.py
Labels: frontend, review-ready

#334 Polishing the hardware documentation
  doc/_static/X8.svg
  doc/introduction/photonic_hardware.rst
  doc/introduction/tutorials.rst
  doc/tutorials/tutorial_X8.rst
  examples/example_job_X8.xbb
  strawberryfields/api/job.py
Labels: docs, review-ready

#339 Add more details to Connection error message
  strawberryfields/api/connection.py
Labels: API

#343 Fix RemoteEngine.run_async kwargs bug, and add test
  strawberryfields/api/connection.py
  strawberryfields/engine.py
  tests/api/test_remote_engine.py
Labels: bug
