Repository XanaduAI/strawberryfields, pull requests merged in 2020-07, with the labels that each got.

#423 Add a function to qchem for coherent state sampling
  .github/CHANGELOG.md
  strawberryfields/apps/qchem/dynamics.py
  tests/apps/qchem/test_dynamics.py
Labels: applications, review-ready

#430 Add a function to qchem for two-mode squeezed state sampling
  .github/CHANGELOG.md
  strawberryfields/apps/qchem/dynamics.py
  tests/apps/qchem/test_dynamics.py
Labels: applications, merge-ready, review-ready

#429 Add connection to device spec API
  .github/CHANGELOG.md
  strawberryfields/api/__init__.py
  strawberryfields/api/connection.py
  strawberryfields/api/devicespec.py
  strawberryfields/circuitspecs/__init__.py
  strawberryfields/circuitspecs/circuit_specs.py
  tests/api/test_connection.py
  tests/api/test_devicespec.py
Labels: review-ready

#434 Add duschinsky function to qchem utils
  .github/CHANGELOG.md
  strawberryfields/apps/qchem/__init__.py
  strawberryfields/apps/qchem/utils.py
  tests/apps/qchem/test_utils_qchem.py
Labels: applications, review-ready

#432 Device spec API implementation
  .travis.yml
  doc/code/sf_compilers.rst
  doc/index.rst
  doc/introduction/circuits.rst
  doc/introduction/ops.rst
  strawberryfields/api/connection.py
  strawberryfields/api/devicespec.py
  strawberryfields/backends/base.py
  strawberryfields/backends/tfbackend/backend.py
  strawberryfields/circuitspecs/X12.py
  strawberryfields/circuitspecs/X8.py
  strawberryfields/circuitspecs/fock.py
  strawberryfields/circuitspecs/xcov.py
  strawberryfields/compilers/__init__.py
  strawberryfields/compilers/compiler.py
  strawberryfields/compilers/fock.py
  strawberryfields/compilers/gaussian.py
  strawberryfields/compilers/gaussian_unitary.py
  strawberryfields/compilers/gbs.py
  strawberryfields/compilers/xcov.py
  strawberryfields/compilers/xunitary.py
  strawberryfields/engine.py
  strawberryfields/io.py
  strawberryfields/ops.py
  strawberryfields/program.py
  strawberryfields/utils/random_numbers_matrices.py
  tests/api/test_connection.py
  tests/api/test_devicespec.py
  tests/api/test_remote_engine.py
  tests/frontend/compilers/test_compiler.py
  tests/frontend/compilers/test_gaussianunitary.py
  tests/frontend/compilers/test_xcov.py
  tests/frontend/compilers/test_xunitary.py
  tests/frontend/test_circuitspecs.py
  tests/frontend/test_circuitspecs_X12.py
  tests/frontend/test_circuitspecs_X8.py
  tests/frontend/test_io.py
  tests/frontend/test_program.py
  tests/integration/test_decompositions_integration.py
  tests/integration/test_parameters_integration.py
Labels: frontend
