Repository XanaduAI/strawberryfields, pull requests merged in 2020-05, with the labels that each got.

#323 Upgrades the TensorFlow backend to TF2.0
  .github/CHANGELOG.md
  .travis.yml
  README.rst
  doc/_static/GateSynthesis.gif
  doc/_static/StateLearning.gif
  doc/_static/minimizing_correlations.gif
  doc/algorithms/quantum_neural_network.rst
  doc/conf.py
  doc/gallery/gate_synthesis/GateSynthesis.ipynb
  doc/gallery/minimizing_correlations/minimizing_correlations.ipynb
  doc/gallery/state_learner/StateLearning.ipynb
  doc/index.rst
  doc/introduction/circuits.rst
  doc/introduction/ml.rst
  doc/introduction/tutorials.rst
  doc/requirements.txt
  doc/tutorials/tutorial_machine_learning.rst
  doc/tutorials/tutorial_teleportation.rst
  examples/optimization.py
  examples/quantum_neural_network.py
  examples_apps/run_gate_synthesis.py
  examples_apps/run_minimizing_correlations.py
  examples_apps/run_state_learner.py
  examples_apps/run_tutorial_machine_learning.py
  requirements.txt
  strawberryfields/backends/tfbackend/__init__.py
  strawberryfields/backends/tfbackend/backend.py
  strawberryfields/backends/tfbackend/circuit.py
  strawberryfields/backends/tfbackend/ops.py
  strawberryfields/backends/tfbackend/states.py
  strawberryfields/engine.py
  strawberryfields/ops.py
  strawberryfields/parameters.py
  tests/backend/test_states_probabilities.py
  tests/backend/test_tf_import.py
  tests/conftest.py
  tests/frontend/test_ops_decompositions.py
  tests/frontend/test_parameters.py
  tests/integration/test_engine_integration.py
  tests/integration/test_tf_integration.py
  tests/integration/test_tf_symbolic.py
  tests/integration/test_utils_integration.py
Labels: backend, review-ready, tensorflow

#383 Norun tutorial
  doc/_static/images/sphx_glr_run_gate_synthesis_001.png
  doc/_static/images/sphx_glr_run_gate_synthesis_002.png
  doc/_static/images/sphx_glr_run_minimizing_correlations_001.png
  doc/_static/images/sphx_glr_run_minimizing_correlations_002.png
  doc/_static/images/sphx_glr_run_state_learner_001.png
  doc/_static/images/sphx_glr_run_state_learner_002.png
  doc/_static/images/sphx_glr_run_state_learner_003.png
  doc/algorithms/quantum_neural_network.rst
  doc/conf.py
  doc/introduction/ml.rst
  doc/introduction/tutorials.rst
  examples_apps/gate_synthesis.py
  examples_apps/machine_learning.py
  examples_apps/minimizing_correlations.py
  examples_apps/state_learner.py
Labels: docs, review-ready

#363 Hardware-friendly decomposition
  .github/CHANGELOG.md
  strawberryfields/decompositions.py
  tests/frontend/test_circuitspecs_X8.py
  tests/frontend/test_decompositions.py
Labels: frontend, merge-ready

#379 Add dark counts to MeasureFock
  .github/CHANGELOG.md
  strawberryfields/io.py
  strawberryfields/ops.py
  tests/frontend/test_io.py
  tests/integration/test_measurement_integration.py
Labels: enhancement, review-ready

#385 Remove traces of Python 3.5
  .github/CHANGELOG.md
  README.rst
  doc/_static/install.html
  doc/development/development_guide.rst
  setup.py
Labels: cleanup, review-ready

#388 Add embedding submodule for training GBS distributions
  strawberryfields/apps/__init__.py
  strawberryfields/apps/train/__init__.py
  strawberryfields/apps/train/embed.py
  tests/apps/test_embed.py
Labels: applications

#389 Added Parity Expectation
  .github/CHANGELOG.md
  strawberryfields/backends/states.py
  tests/backend/test_states.py
Labels: merge-ready

#281 Moved CV conventions into ops.py docstrings
  doc/conf.py
  doc/custom_directives.py
  doc/xanadu_theme/static/xanadu.css_t
  strawberryfields/ops.py
Labels: docs

#387 Add GBS parametrization for training variational GBS circuits
  strawberryfields/apps/train/__init__.py
  strawberryfields/apps/train/param.py
  tests/apps/test_train.py
Labels: applications, enhancement, review-ready

#394 Adds the Parity Operator for States in the Gaussian Backend (WIP)
  .github/CHANGELOG.md
  strawberryfields/backends/states.py
  tests/backend/test_states.py
Labels: WIP, enhancement

#358 X series compiler
  .github/CHANGELOG.md
  strawberryfields/circuitspecs/__init__.py
  strawberryfields/circuitspecs/circuit_specs.py
  strawberryfields/circuitspecs/gaussian_unitary.py
  strawberryfields/circuitspecs/xcov.py
  strawberryfields/circuitspecs/xunitary.py
  tests/frontend/test_circuitspecs_xcov.py
  tests/frontend/test_circuitspecs_xunitary.py
Labels: frontend

#391 Add KL divergence to cost module
  strawberryfields/apps/train/__init__.py
  strawberryfields/apps/train/cost.py
  tests/apps/test_cost.py
Labels: applications
