Repository XanaduAI/strawberryfields, pull requests merged in 2020-02, with the labels that each got.

#289 S2gate to fock
  .github/CHANGELOG.md
  strawberryfields/backends/fockbackend/backend.py
  strawberryfields/backends/fockbackend/circuit.py
  strawberryfields/backends/fockbackend/ops.py
  strawberryfields/circuitspecs/fock.py
  strawberryfields/ops.py
  tests/backend/test_twomode_squeezing_operation.py
Labels: backend, frontend, review-ready

#290 Remove unnecessary else
  .github/CHANGELOG.md
  strawberryfields/backends/fockbackend/ops.py
Labels: cleanup, review-ready

#287 Use thewalrus to calculate displacement, squeezing and beamsplitter in the Fock backend
  .github/CHANGELOG.md
  requirements.txt
  strawberryfields/backends/fockbackend/ops.py
Labels: backend, review-ready

#292 Custom contraction for beamsplitter, two-mode squeezing and diagonal operators
  .github/CHANGELOG.md
  strawberryfields/backends/fockbackend/circuit.py
  strawberryfields/backends/fockbackend/ops.py
  tests/backend/test_beamsplitter_operation.py
  tests/backend/test_twomode_squeezing_operation.py
Labels: backend, enhancement, review-ready

#293 Fockbackend apply-gate cleanup
  .github/CHANGELOG.md
  strawberryfields/backends/fockbackend/circuit.py
  strawberryfields/backends/fockbackend/ops.py
Labels: backend, cleanup, review-ready

#295 Apps layer: Add WAW adjacency matrix rescaling function
  .github/CHANGELOG.md
  Makefile
  strawberryfields/apps/sample.py
  tests/apps/test_sample.py
Labels: applications, review-ready

#296 Apps: Update clique functions to accept node weights
  .github/CHANGELOG.md
  strawberryfields/apps/clique.py
  tests/apps/test_clique.py
Labels: applications, review-ready

#300 Unified backend results
  .github/CHANGELOG.md
  strawberryfields/apps/sample.py
  strawberryfields/engine.py
  tests/apps/test_sample.py
  tests/frontend/test_engine.py
  tests/integration/test_engine_integration.py
Labels: backend, review-ready

#298 Config refactor
  .github/CHANGELOG.md
  doc/introduction/configuration.rst
  strawberryfields/configuration.py
  tests/frontend/test_api_client.py
  tests/frontend/test_configuration.py
  tests/frontend/test_engine.py
Labels: API, review-ready

#297 Apps: Update subgraph functions to accept node weights
  .github/CHANGELOG.md
  strawberryfields/apps/clique.py
  strawberryfields/apps/subgraph.py
  tests/apps/test_subgraph.py
Labels: applications, review-ready

#303 Correct typo in changelog
  .github/CHANGELOG.md
Labels: docs

#305 Adding numba to requirements
  requirements.txt
  setup.py
Labels: bug

#301 Fixes a bug in the MZgate convention by reversing the internal and external phase arguments.
  .github/CHANGELOG.md
  strawberryfields/circuitspecs/__init__.py
  strawberryfields/circuitspecs/chip0.py
  strawberryfields/circuitspecs/chip2.py
  strawberryfields/ops.py
  tests/frontend/test_circuitspecs_chip0.py
  tests/frontend/test_circuitspecs_chip2.py
  tests/frontend/test_engine.py
Labels: bug

#306 Add the store account function
  .github/CHANGELOG.md
  doc/introduction/configuration.rst
  strawberryfields/__init__.py
  strawberryfields/configuration.py
  tests/conftest.py
  tests/frontend/test_configuration.py
Labels: API, review-ready

#294 Refactor remote job engine to Engine/Connection API
  .github/CHANGELOG.md
  .travis.yml
  Makefile
  doc/code/sf_api.rst
  doc/code/sf_api_client.rst
  doc/index.rst
  starship
  strawberryfields/api/__init__.py
  strawberryfields/api/connection.py
  strawberryfields/api/job.py
  strawberryfields/api/result.py
  strawberryfields/api_client.py
  strawberryfields/engine.py
  tests/api/__init__.py
  tests/api/conftest.py
  tests/api/test_connection.py
  tests/api/test_job.py
  tests/api/test_result.py
  tests/api/test_starship_engine.py
  tests/frontend/test_api_client.py
  tests/frontend/test_circuitspecs_gaussianunitary.py
  tests/frontend/test_engine.py
  tests/pytest.ini
Labels: API, review-ready
