Repository XanaduAI/strawberryfields, pull requests merged in 2020-04, with the labels that each got.

#345 Fix image in hardware tutorial
  doc/_static/X8.png
  doc/tutorials/tutorial_X8.rst
Labels: docs, review-ready

#344 Bump version number to 0.13.0rc0
  .github/CHANGELOG.md
  doc/requirements.txt
  strawberryfields/_version.py
Labels: review-ready

#347 Logging job ID with engine.run
  LICENSE
  strawberryfields/api/connection.py
  strawberryfields/api/job.py
  strawberryfields/configuration.py
  strawberryfields/engine.py
  strawberryfields/logger.py
  tests/frontend/test_logger.py
Labels: API, review-ready

#364 Fixes bug where negative probabilities can be calculated during Homodyne measurement in the Fock backend
  .github/CHANGELOG.md
  strawberryfields/backends/fockbackend/circuit.py
Labels: bug, review-ready

#365 Bump version number for 0.13.0 release
  .github/CHANGELOG.md
  doc/code/sf_cli.rst
  doc/code/sf_configuration.rst
  strawberryfields/__init__.py
  strawberryfields/_version.py
  strawberryfields/api/connection.py
Labels: review-ready

#367 Fix printing of results object when it contains no state
  .github/CHANGELOG.md
  strawberryfields/api/connection.py
  strawberryfields/api/result.py
  tests/api/test_result.py
Labels: bug, review-ready

#348 Number expectation
  .github/CHANGELOG.md
  strawberryfields/backends/states.py
  tests/backend/test_states.py
Labels: backend, merge-ready

#370 Add error details for failed remote job
  .github/CHANGELOG.md
  strawberryfields/api/connection.py
  strawberryfields/api/job.py
  strawberryfields/engine.py
  tests/api/test_connection.py
  tests/api/test_remote_engine.py
Labels: API

#320 [TF2] Fix casting of TensorFlow tensors in the frontend
  strawberryfields/backends/tfbackend/circuit.py
  strawberryfields/ops.py
  strawberryfields/parameters.py
  tests/conftest.py
  tests/frontend/test_ops_decompositions.py
  tests/frontend/test_parameters.py
  tests/integration/test_algorithms.py
Labels: frontend, review-ready, tensorflow

#372 Updates the optimization tutorial for TensorFlow 2.0
  doc/conf.py
  doc/introduction/ml.rst
  doc/introduction/tutorials.rst
  doc/requirements.txt
  doc/tutorials/tutorial_machine_learning.rst
  examples/optimization.py
  examples_apps/run_tutorial_machine_learning.py
Labels: docs, review-ready

#377 Fix einsum gradient by using old TF einsum
  strawberryfields/backends/tfbackend/circuit.py
  strawberryfields/backends/tfbackend/ops.py
  strawberryfields/backends/tfbackend/states.py
  tests/integration/test_tf_integration.py
Labels: review-ready, tensorflow

#373 Updates the state learning tutorial for TensorFlow 2.0
  README.rst
  doc/_static/StateLearning.gif
  doc/gallery/state_learner/StateLearning.ipynb
  doc/index.rst
  doc/introduction/ml.rst
  doc/introduction/tutorials.rst
  examples_apps/run_state_learner.py
Labels: docs, review-ready

#375 Updates the minimizing correlations tutorial for TensorFlow 2.0
  doc/_static/minimizing_correlations.gif
  doc/gallery/minimizing_correlations/minimizing_correlations.ipynb
  doc/introduction/ml.rst
  doc/introduction/tutorials.rst
  examples_apps/run_minimizing_correlations.py
Labels: docs

#374 Updates the gate synthesis tutorial for TensorFlow 2.0
  doc/_static/GateSynthesis.gif
  doc/gallery/gate_synthesis/GateSynthesis.ipynb
  doc/introduction/ml.rst
  doc/introduction/tutorials.rst
  examples_apps/run_gate_synthesis.py
Labels: docs
